services:
  backend:
    build:
      context: ./backend/Altairis.Api
      dockerfile: Dockerfile
    ports:
      - "5113:8080"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - altairis-data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  altairis-data:

